### ISSUE TITLE
Analyseren hoe zij Harry hebben gemaakt (Code)

### ISSUE THREAD

**Issue by rutgerkock** [fdnd-agency/buurtcampus-oost#122]
**User Story:** 
Als bezoeker wil ik op een speelse manier meer informatie over… plantjes verzorgen.

**Taak**
Analyseren hoe zij Harry hebben gemaakt (Code)

![Image](https://github.com/user-attachments/assets/96e276ec-a4a0-4ffc-b03f-75852fcc1ea7)

Link CMD site met HARRY: https://buurtcampus-oost.onrender.com/zaden/milkmaid
https://buurtcampus-oost.onrender.com/stekjes/monstera

**Comment by Lmikkers** [comment]
## Analyseren Harry
Ik heb gekeken hoe zij Harry hebben gemaakt en hoe het werkt. In Figma heb ik in het kort de bevindingen opgeschreven. Zo zie je dat ze gebruik maken van een SVG en ook van een .ai bestand. Ze hebben ook meerdere Harries, met verschillende moods.

![Image](https://github.com/user-attachments/assets/d0bae2d8-5e66-4e10-8e0c-b2d7a02ef3e3)
