### ISSUE TITLE
Accessibilty features op CMD livesite analyseren

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#125]
**User Story:**
Als bezoeker wil ik toegankelijkheid features zien en kunnen aanpassen

**Taak:**
Accessibilty features op CMD livesite analyseren

**Comment by Annevd** [comment]
## Bronnen

[Concept accessibility](https://github.com/N13L5A97/BiebinBloei/wiki/accessibility)
[Techniek accessibility menu](https://github.com/N13L5A97/BiebinBloei/wiki/accessibility-menu)

**Comment by Annevd** [comment]
## 26/9 Accessibility features concept analyse

### Font-scale
Omdat de grootste doelgroep van de bibliotheek vooral mensen op leeftijd zijn, kwam het team van CMD met het idee om een functie te bouwen waarmee mensen makkelijk de tekst grootte kunnen aanpassen. Dit is niet alleen fijn voor ouderen maar ook voor mensen die minder goed kunnen zien dan gemiddeld.

### Vertaal Functie
Een ander groot deel van de bezoekers van de bibliotheek heeft een migratie achtergrond. Dit kan inhouden dat hun Nederlands niet heel goed is en dat de website misschien niet toegankelijk genoeg zou zijn voor hen. Daarvoor bedacht het team van CMD de mogelijkheid om de website te kunnen vertalen naar de gewenste taal.

### Contrast
Het originele design is getest op kleur contrast zodat dit in overeenstemming is met de WCAG.

### Dark Mode
Niet iedereen kan even goed tegen licht of heeft simpel gewoon voorkeur voor donkere modus op hun scherm. Daarvoor wilde het team van CMD zorgen dat de website ook een donkere modus heeft om iedereen een zo'n prettig mogelijke ervaring te geven.

### Reduced Motion
Aangezien het team van CMD ook veel animaties wilden gaan toevoegen is het belangrijk dat deze uitgezet kunnen worden. Sommige mensen kunnen dit als niet prettig ervaren. Hiervoor willen we reduced motion toevoegen zodat ze wel kunnen meegenieten van de seizoensgebonden "lagen" die we toevoegen op de website zonder dat ze daar last van hebben.

---

Bovenstaande tekst was dus het concept bedacht door studenten van de minor CMD.

De font-scale, dark mode en vertaalfunctie bevinden zich al op de website. Reduced motion nog niet, dit zou dus ook nog geïmplementeerd kunnen worden.

**Comment by Annevd** [comment]
## 26/9 Accessibility features techniek analyse 2

### Font scale

Ook deze functie is gemaakt met puur CSS doormiddel van een checkbox en `has()`.

```HTML
<div class="accessibilityMenu">
    <label class="accessibilityIcon">
        <input type="checkbox" id="menu">
        <img src="/images/accessibility.png">
    </label>
    <div class="accessibilityContent">
        <ul>
            <li>                        
                <label>
                    <input type="checkbox" id="font-size">
                    Grotere Letters
                </label>
            </li>
            <!-- rest van de li's -->
        </ul>
    </div>
</div>
```

```CSS
/* if checkbox is checked */
html:has(#font-size:checked){
    --font-size-p: calc(clamp(1rem, 2vw, 1.2rem) * 1.5);
}
```

**Comment by Annevd** [comment]
## 26/9 Accessibility features techniek analyse 3

### Dark mode

**Comment by Annevd** [comment]
## 26/9 Accessibility features techniek analyse 4

### Vertalen via Google translate

**Comment by Nazneen05x** [comment]
Wow Anne! Wat goed! Mooie analyse! 🪴
