### ISSUE TITLE
Accessibility features op CMD livesite testen

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#127]
**User story:**
Als bezoeker wil ik toegankelijkheid features zien en kunnen aanpassen

**Taak:**
Accessibility features op CMD livesite testen, wat werkt wel, wat werkt niet?

**Comment by Annevd** [comment]
## 25/9

Op mac werkt dark mode niet.

**Comment by Annevd** [comment]
## 26/9 Testen Accessibility features

### De button zelf

**Functionaliteit:**

De accessibility button op zich werkt overal goed. Op kleine en grote schermen is het duidelijk te zien en opent het menu zonder haperingen.

### Het menu

**Functionaliteit:**
- De dark mode checkbox werkt goed, je kan hem zonder moeite aan en uit zetten.
- Ook de checkbox voor grotere letters werkt zoals behoren.
- De vertaal optie daarentegen werkt niet goed. Toen ik voor het eerst de verschillende functies in het menu gebruikte werkte alles goed, en kon ik de site vertalen naar verschillende talen. Maar na een aantal keer dark mode/grotere letters te hebben aan/uit geklikt, was het selecteervakje weg, en kon ik geen talen meer kiezen. Na een refresh was dit weer terug.

**Ontwerp:**

**Comment by Nazneen05x** [comment]
@Annevd Goed gedaan! mooie analyse!
