### ISSUE TITLE
Button maken voor accessibility tools (html/css)

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#133]
**User story:**
Als bezoeker wil ik toegankelijkheid features zien en kunnen aanpassen

**Taak:**
Button maken voor accessibility tools (html/css)

**Comment by Annevd** [comment]
## 3/10 Accessibility button

Op basis van mijn ontwerp en de oude code van de web minor heb ik de button voor de accessibility tools gemaakt.

![Image](https://github.com/user-attachments/assets/3df2a361-d467-485c-8a0a-2ab5e811269f)

In issue #139 & #142 leg ik meer uit over de code.

**Comment by Nazneen05x** [comment]
Mooi gedocumenteerd!
