### ISSUE TITLE
analyseren van accessibility tools button

### ISSUE THREAD

**Issue by wingsvn** [fdnd-agency/buurtcampus-oost#155]
Hoe komt de button er uit te zien?
waar komt de button te staan? 
Hoe worden de features weergeven? 
etc etc..

**Comment by wingsvn** [comment]
**welke accessibility tools willen we meenemen voor de bieb-in-bloei website?**
dark modus, grotere letters, vertaling en eventueel een audio/voorlees knop

**Comment by wingsvn** [comment]
De accessibility tools button op de CMD bieb-in-bloei website ziet er als volgt uit:
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/586bcd86-6ccb-4682-8391-5f9b3204c49a">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/c6a1c991-a134-4703-8476-171c96dad617">

**Comment by wingsvn** [comment]
ik heb verschillende websites bezocht om te onderzoeken hoe de accessibility features op hun website worden weergegeven.

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/7b466bae-8b58-45d1-b75f-036065c3c29d">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/e7d26980-ce82-4617-b5dd-7226f36ff757">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/f46784ee-c61d-452d-ae05-7e76851c701f">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/1a044c93-83c7-41cd-acac-7ee41eb1cecc">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/eecb05d9-7b04-46f7-903b-ff15f3686d29">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/c3dfcdfa-4af8-42ac-9d80-2abe5cd8bf33">
<img width="100" alt="image" src="https://github.com/user-attachments/assets/eba3ec96-817e-472f-8baf-b861a53eefe6">
<img width="100" alt="image" src="https://github.com/user-attachments/assets/a0342243-ef0b-42ad-81c6-0836d11fe9c7">
<img width="200" alt="image" src="https://github.com/user-attachments/assets/8d4c73eb-69fd-4565-9917-4ed9706433e8">

Verder heb ik ook via Pinterest inspiratie opgedaan:

<img width="200" alt="image" src="https://github.com/user-attachments/assets/bb94904b-024f-4b07-b6c9-fdfc0edc95f2"> <img width="135" alt="image" src="https://github.com/user-attachments/assets/7132b4e0-bbfd-4a72-9d9b-92981ddac12b"> <img width="200" alt="image" src="https://github.com/user-attachments/assets/2c89010c-4436-48ac-96b1-82e7ad7d5ffa">
<img width="200" alt="image" src="https://github.com/user-attachments/assets/5592bb13-5d15-4702-9af9-627857c4f3f5"> <img width="200" alt="image" src="https://github.com/user-attachments/assets/14155545-4bbe-420b-aca1-b6e4e888e7db">

**Comment by Nazneen05x** [comment]
duidelijke analyse en goeie inspiratie gevonden. Ben benieuwd naar de eindresultaat 😊
