### ISSUE TITLE
HyGraph content analyseren

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#157]
Analyseer hoe alle Hygraph content in elkaar zit zodat de nieuwe content kan worden toegevoegd.

**Comment by Nazneen05x** [comment]
Vragen:

**Comment by Annevd** [comment]
## Missende content

- Agenda wordt nog niet uit Hygraph gehaald

**Comment by Nazneen05x** [comment]
# Inventarislijst Hygraph Content:

## Homepage (homecampus)
Agenda - carousel component 
CampusInfo
CardSlide
HeroSlider
PartnersInfo

## Stekjes pagina
overViewPage

## Stekjes detailpagina
Stekjes

## Zaden pagina
overViewPage

## Zaden detailpagina
Zaden

## Geveltuin pagina
Geveltuin

## Agenda pagina
Agenda
AgendaText


## Partners pagina 
Wordt andere pagina

## Contact pagina
Contact


## Alle pagina’s
Footer
heroHeaders

## Overige 
Categorie n.v.t 
Gebruiker n.v.t 
KastHeader  n.v.t 
Stekje Header n.v.t
