### ISSUE TITLE
Stekjes pagina | collectie klikbaar

### ISSUE THREAD

**Issue by Lmikkers** [fdnd-agency/buurtcampus-oost#183]
Alleen de titel is klikbaar, logischer om heel het item klikbaar te maken. Dit kan door er een `<a>` omheen te zetten 

<img width="1440" alt="Scherm­afbeelding 2024-10-04 om 15 27 46" src="https://github.com/user-attachments/assets/75e9a37e-91eb-4d24-bb73-a4fcde3dd018">

**Comment by Lmikkers** [comment]
Ik heb de `articles` klikbaar gemaakt en heb een hover effect toegevoegd. Ook heb ik ervoor gezorgd dat het contrast is verhoogd door een overlay op de `h3` te zetten

https://github.com/user-attachments/assets/96ed7ce3-57fd-440b-a565-d15175d0758d

**Comment by Nazneen05x** [comment]
@Lmikkers Ik had in het begin van de semester een wave test uitgevoerd op alle pagina's. bij de stekjes pagina was de contrast niet goed en bij andere pagina's. Ik ben benieuwd of het nu wel goed is bij de stekjes pagina, kan je het checken?😊

https://wave.webaim.org/
