### ISSUE TITLE
Geveltuin listitems afbeelding wazig

### ISSUE THREAD

**Issue by Lmikkers** [fdnd-agency/buurtcampus-oost#193]
De afbeelding van de `list item` is wazig, ik heb gekeken en het is een `png`, deze kunnen we vervangen voor een `svg`.

<img width="1440" alt="Scherm­afbeelding 2024-10-09 om 16 07 32" src="https://github.com/user-attachments/assets/6ce43af5-fbd1-47c8-b973-04faad640511">
<img width="807" alt="Scherm­afbeelding 2024-10-09 om 16 00 32" src="https://github.com/user-attachments/assets/ede955b5-60c0-4f70-bb2e-026bf198baee">

**Comment by Nazneen05x** [comment]
@Lmikkers Thanks had ik niet gemerkt! ga het oppakken!
