### ISSUE TITLE
Uitzoeken hoe je een form submit werkend maakt voor publicatie

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#200]

**Comment by Annevd** [comment]
## 19/11 Form submit analyse

Om te onderzoeken hoe een formulier echt ergens naartoe verstuurd wordt, heb ik eerste de code in het form die er al was geanalyseerd. Hier haalde ik uit dat dat via Web3Forms gaat. Er wordt al gebruik gemaakt van een acceskey.

**Dit is hoe het werkt:**

1. Bij het aanmaken van een account op Web3Forms geef je een e-mailadres (of meerdere adressen) op om de formuliergegevens te ontvangen.
2. Web3Forms genereert een unieke toegangssleutel (acceskey) die is gekoppeld aan een account. Deze sleutel wordt in het formulier gebruikt en zorgt ervoor dat alleen gegevens van dat formulier naar die e-mail worden gestuurd.
3. Wanneer iemand het formulier invult en verzendt, controleert de Web3Forms API of de toegangssleutel geldig is. Als dit het geval is, worden de gegevens van het formulier verwerkt en doorgestuurd naar het e-mailadres dat aan het account is gekoppeld.
4. Na verwerking stuurt Web3Forms de gegevens van de inzending naar het door jou opgegeven e-mailadres.

**Hoe de code werkt:**
- In de form gebruik je de `action` en `method` attributen om aan te geven waar het formulier naar wordt verstuurd en hoe het formulier verstuurd wordt.
```HTML
<form action="https://api.web3forms.com/submit" method="POST">

    <input type="hidden" name="access_key" value="YOUR_ACCESS_KEY_HERE">
```
- Het `action="https://api.web3forms.com/submit"` attribuut specificeert de URL waar de formuliergegevens naartoe worden gestuurd.
- Het `method="POST"` attribuut zorgt ervoor dat de gegevens van het formulier worden verzonden in de body van een HTTP POST-verzoek.
- Het `<input type="hidden" name="access_key" value="YOUR_ACCESS_KEY_HERE">` bevat een toegangssleutel die het verzoek authenticeren bij de Web3Forms API.

Wanneer de gebruiker het formulier indient, worden de ingevoerde gegevens verpakt als "key-value pairs" (gebaseerd op de name-attributen van de invoervelden) en verzonden naar https://api.web3forms.com/submit.

De Web3Forms API verwerkt deze gegevens. Afhankelijk van de configuratie kan de API een e-mail sturen met de inhoud van het formulier, de gegevens opslaan of een andere actie uitvoeren die je hebt ingesteld via het Web3Forms-dashboard.

**Comment by Nazneen05x** [comment]
Goede en duidelijke analyse Anne! Duidelijk uitleg over web3Forms. Deze ga ik later gebruiken voor de geveltuin form😊
