### ISSUE TITLE
Sprint review - Retrospect - 27/ 29/11/24

### ISSUE THREAD

**Issue by Nazneen05x** [fdnd-agency/buurtcampus-oost#215]
### Rollen
Larissa -> Notulist/presentator
Wing San -> Notulist/presentator
Anne -> Notulist/presentator
Nazneen -> Timekeeper/presentator/notulist

### Planning Presenteren

Larissa:

- Harry

Anne:

- Toegankelijkheidsmenu
- Contact component 

Nazneen:

- Projectplan
-  Vragen
- Ontwerpen menu

Wingsan:

- Agendapagina

### Vragen/Knelpunten

Form/aanmeld:

### Anne 
- Hoe zit het met het versturen van het contactformulier? staat dat al aan het goede e-mailadres gelinkt? zo niet moeten we dat even regelen. Ook vragen of het limiet van 250 submissions per maand genoeg is. Anders andere oplossing vinden bijvoorbeeld `mail:to`

- Het formulier heeft geen hoog genoeg contrast. Dit kun je oplossen door een border of box-shadow. Vragen of ze dat goed vind.

- Het verbeterde contact formulier component laten zien en vragen of ze dingen daarvan wil verwerken in de release candidate

### Wingsan 

- Als je je via de agenda pagina wilt aanmelden voor de workshop wordt je doorgestuurd naar de contact pagina. Is dit goed zo of willen we een aparte pop-up op de agenda pagina zelf met hetzelfde contact formulier? Dit zou wel betekenen dat dezelfde functie op 2 pagina's te vinden zijn.. 

Overige vragen:

### Anne
- Aangeven dat het niet zeker is of we het toegankelijkheidsmenu in zijn volledigheid af krijgen. Als back-up aanbieden om wel dark mode te kunnen bouwen met een `prefers-color-scheme`

### Nazneen
- Welke pagina's zijn het belangrijkst? Wordt het meest bezocht en gebruikt door de gebruikers?
- Hoe belangrijk is de agenda? en hoe actueel is het straks?
- Stekjes die op de pagina zijn deze actueel? 
- Content heeft nu echt prioriteit, liefts zo snel mogelijk. Is het ook een goede weerspiegeling van wat er echt is in de bieb? Anders kan je beter een informatie pagina er van maken.
- Welke afbeelding zijn voor de geveltuin en stekjes?

**Comment by Nazneen05x** [comment]
## Kampvuursessie 🔥

**Comment by Lmikkers** [comment]
### Larissa samenvatting:

1. Hoe ging de samenwerking? Wat ging goed?
De samenwerking verliep goed, iedereen werkte zelfstandig aan zijn taken en hield elkaar op de hoogte tijdens stand-ups. In deze sprint hebben we voornamelijk individueel gewerkt, waardoor we minder direct hebben samengewerkt. Dit hebben we later besproken en afgestemd tijdens de stand-ups.

3. Wat kan de volgende keer beter als team, Wat ging er minder goed?

4.  Doelen behaald die in het team canvas staan?

Tips - wat kan beter🫂?

Tops - complimenten🫂!

**Comment by Annevd** [comment]
## Feedback opdrachtgever

### Algemeen

- Skip to content
- FAQ op contactpagina
- Samenwerken ? met vraagteken andere kleur + harry op partners pagina

### Larissa/Rutger

- HArry op elke pagina verwelkomen
- Harry als faviocn met seizoenen
- harry paraplu
- harry bliksem
- harry word samengevoegd
- Stekjes details goed

### Anne

- Plantje
- shadow
- email regelen
- dark mode

### Wing

- Content voor agenda wordt nog aangeleverd
- Buttons
- Pagina zag er mooi uit
- Prijs veranderen naar gratis

### Nazneen

- Dropdwon menu ontwerp: 3de, aesthetic
- Test op dropdown 
- Welke paginas zijn t belangrijskt? komt nog mail
- Agenda is voor lancering niet t belangrijkst
- Informatiepagina met veelvoorkomende stekjes

**Comment by Nazneen05x** [comment]
Ik heb het projectplan en  dropdown menu ontwerpen gepresenteerd tijdens de sprint review aan de opdrachtgever en medestudenten. Verder had ik een aantal vragen opgesteld, deze heb ik ook gesteld aan de opdrachtgever tijdens de sprint review.

....

.....
