### ISSUE TITLE
Redesign - home page

### ISSUE THREAD

**Issue by Duneyasaleh** [fdnd-agency/buurtcampus-oost#30]
We gaan onderzoek doen naar hoe we de homepage gaan ontwerpen op basis van het bestaande design en de nieuwe structuur die we hebben ontvangen. Het plan is om tegen **23 april** een eerste versie gereed te hebben, zodat we deze kunnen bespreken met de opdrachtgever en feedback kunnen ontvangen.

**Comment by JalalToufik** [comment]
Ik heb in na aantal schetsjes mijn ontwerp uitgewerkt in Figma, met de goedkeuring van de opdrachtgever.
